version: '3.9'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local
